### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by Lachlannr** [illuZion9999/Rzy-Protector-V2-unpacker#3]
can you plz fix the unpacker

**Comment by illuZion9999** [comment]
What error do you get when using it?
Please provide the file as well.

**Comment by Lachlannr** [comment]
it don't do what it's supposed to do go try it your self the Protector is open source now

**Comment by Lachlannr** [comment]
https://github.com/search?q=RzyProtector

**Comment by illuZion9999** [comment]
Next time you open an issue, be sure to read the project's description before. This isn't supposed to deobfuscated Rzy Protector but Rzy Protector **V2**. Plus, you don't even give any details regarding your problem, which makes it kinda hard to solve.
